### ISSUE TITLE
`mksquashfs` errors since both `SOURCE_DATE_EPOCH` and `-all-time`/`mkfs-time` flags are set

### ISSUE THREAD

**Issue by sagar794** [SpacingBat3/ReForged#13]
## Summary
`mksquashfs` version 4.4+ will throw a [error](https://github.com/plougher/squashfs-tools/blob/4f1fae8fec44a72d100500ea79accb86d93f2be3/squashfs-tools/mksquashfs.c#L6162) if both the `SOURCE_DATE_EPOCH` environment variable and `-all-time`/`-mkfs-time` flags are set. 

This is an issue since this package will always [add the `-all-time`/`-mkfs-time` flags](https://github.com/SpacingBat3/ReForged/blob/45d28765c288c261a24788b999a9122b249ca47f/makers/appimage/src/main.ts#L326). If the intention is to always set the  `-all-time`/`-mkfs-time` flags then the `SOURCE_DATE_EPOCH` environment variable should not be passed when `mksquash` version 4.4+ is being used.

Also, if possible, can the `stderr` be printed out when a non-zero exit code is returned by `mksquashfs`? An error code of 1 gets returned for the error mentioned above which made it difficult to track down the root cause. Potentially something like this? This hasn't been tested yet.

```
mkSquashFS.on("close", (...args) => {
  mkSquashFS.stderr.pipe(process.stderr)
  event.emit("close",...args)
});
```
## Additional Resources
- [`mksquashfs` 4.4 release notes](https://github.com/plougher/squashfs-tools/blob/4f1fae8fec44a72d100500ea79accb86d93f2be3/RELEASE-READMEs/README-4.4#L124-L127)

**Comment by SpacingBat3** [comment]
> Also, if possible, can the stderr be printed out when a non-zero exit code is returned by mksquashfs? An error code of 1 gets returned for the error mentioned above which made it difficult to track down the root cause. Potentially something like this? This hasn't been tested yet.

Nah, that code snippet would be in conflict with the Forge's way of logging messages to stdout itself. However maybe I'll be able to transform the `mkSquashFS` `stderr` in a way it will be thrown with the error message once there will be a non-zero status code…

> If the intention is to always set the -all-time/-mkfs-time flags then the SOURCE_DATE_EPOCH environment variable should not be passed when mksquash version 4.4+ is being used.

I think my makers should respect `SOURCE_DATE_EPOCH` if set. Also I think I've added these flags to code because AppImageKit does this as well and the intention was to produce similar images to AppImageKit. But again, I want to be compilant with `SOURCE_DATE_EPOCH`, so possibly I'll just won't add these flags to ARGV once `SOURCE_DATE_EPOCH` is set in the env and is a non-empty string.

I'll probably work on this later tho, right now I need to focus on my exams.

**Comment by sagar794** [comment]
Thank you for taking the time to read through the issue. Good luck on your exams!

**Comment by SpacingBat3** [comment]
(Ugh, I've messed with the sources here, I think I have unpublished commits on my PC (yet have them published on NPM), which I have currently no physical access to, so there are obviously changes that need to be pushed before I can work on anything. 😖)
