### ISSUE TITLE
`maker-appimage` fails to build on `squashfs-tools<4.4`

### ISSUE THREAD

**Issue by oold** [SpacingBat3/ReForged#8]
Running `electron-forge make` fails to create the AppImage file:
```
[oold@PC11319 my-electron-app]$ yarn run make
yarn run v1.22.19
$ electron-forge make
✔ Checking your system
✔ Loading configuration
✔ Resolving make targets
✔ Loading configuration
✔ Resolving make targets
  › Making for the following targets: AppImage
✔ Running package command
  ✔ Preparing to package application
  ✔ Running packaging hooks
    ✔ Running generateAssets hook
    ✔ Running prePackage hook
      ✔ [plugin-webpack] Preparing native dependencies: 1 / 1
      ✔ [plugin-webpack] Building webpack bundles
  ✔ Packaging application
    ✔ Packaging for x64 on linux [3s]
  ✔ Running postPackage hook
✔ Running preMake hook
❯ Making distributables
  ✖ Making a AppImage distributable for linux/x64
    › ENOENT: no such file or directory, open '/home/oold/my-electron-app/out/make/AppImage/x64/my-electron-app-0.0.0…
◼ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: ENOENT: no such file or directory, open '/home/oold/my-electron-app/out/make/AppImage/x64/my-electron-app-0.0.0-x64.AppImage'
```

**Comment by SpacingBat3** [comment]
Unable to reproduce, could you share more info (like `DEBUG=*` logs and your Forge config and version)?

**Comment by oold** [comment]
- Forge version: `6.0.5`
- Forge config:
<details>

```ts
import type { ForgeConfig } from '@electron-forge/shared-types';
import { MakerZIP } from '@electron-forge/maker-zip';
import { WebpackPlugin } from '@electron-forge/plugin-webpack';
import { MakerAppImage } from '@reforged/maker-appimage';

import { mainConfig } from './webpack.main.config';
import { rendererConfig } from './webpack.renderer.config';

const config: ForgeConfig = {
  packagerConfig: {},
  rebuildConfig: {},
  makers: [
    new MakerZIP({}, ['win32']),
    new MakerAppImage({
      options: {
        icon: 'Package.png',
      },
    }),
  ],
  plugins: [
    new WebpackPlugin({
      mainConfig,
      renderer: {
        config: rendererConfig,
        entryPoints: [
          {
            html: './src/app.html',
            js: './src/app.tsx',
            name: 'main_window',
            preload: {
              js: './src/preload.ts',
            },
          },
          {
            html: './src/app.html',
            js: './src/app.tsx',
            name: 'second_window',
            preload: {
              js: './src/preload.ts',
            },
          },
        ],
      },
    }),
  ],
};

export default config;
```

</details></li>

- [build.log](https://github.com/SpacingBat3/ReForged/files/11100452/build.log)

---

**MOD EDIT**: Just made things a bit more compact and added some formatting.

**Comment by SpacingBat3** [comment]
@oold Sorry, I still couldn't reproduce it (I haven't tested maker with WebPack plugin, but it sounds odd for it to be a cause of this failure). I have some guesses (with some notes about them) what could be the cause of this issue:

- `mksquashfs` somehow does not create the SquashFS image for the AppImage – On which distro you were building it on? What's version you had installed of `squashfs-tools` (if any)?
- The issue is on Electron Forge side and class methods implemented by it such as `MakerBase.ensureFile` fails for unknown reason – This is more likely to happen if build fails almost immediately (by looking at logs it might be actually?).

Anyway, the error itself is emitted by Node's `fs` API (most likely by methods associated to reading file content, like `fs.readFile`). The error suggests it is done while reading the *AppImage*, which is only done after generating a SquashFS image to merge it with the `runtime` stored in maker's memory. This is the only place in code where this error could be emmited:

https://github.com/SpacingBat3/ReForged/blob/cf1d0811e126fd0073a33e001228dadba1cf2f52/makers/appimage/src/utils.ts#L196-L208

…but during this function to execute, the file has to be there already on this given time emitted by `mksquashfs`, so if it fails I can do nothing about it. For now I can only take a look and improve error logging there to make sure it is caused in this specific place as well as to handle non-zero exit code of `mksquashfs` if that could also help investigating this issue 😕.

**Comment by oold** [comment]
I'll check my `mksquashfs` version tomorrow. The distribution itself is Oracle Linux 8.5.

**Comment by oold** [comment]
```
[oold@PC11319 ~]$ mksquashfs -version
mksquashfs version 4.3-git (2014/06/09)
copyright (C) 2014 Phillip Lougher <phillip@squashfs.org.uk>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
```

**Comment by oold** [comment]
Alright, so I just installed OL 9 and it works with the `mksquashfs` available from its package sources.
```
[root@PC11319 my-electron-app]# mksquashfs -version
mksquashfs version 4.4-git.1 (2020/10/30)
copyright (C) 2020 Phillip Lougher <phillip@squashfs.org.uk>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
```
Seems like the previous one was just too old.

**Comment by SpacingBat3** [comment]
> Seems like the previous one was just too old.

I've improved the compatibility with the older `mksquashfs`, I've checked the support for the command-line arguments and made them applied according to installed version of `mksquashfs` in the OS. However, `squashfs-tools>=4.4` is still recommended to be installed for all features / flags to be applied.
